// @feature observability-ui
// @spec docs/features/observability-ui.md
// @entrypoint frontend-build
import { cpSync, mkdirSync, rmSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { build } from "esbuild";

const options = { cwd: import.meta.dirname, stdio: "inherit" };
rmSync("dist", { recursive: true, force: true });
mkdirSync("dist", { recursive: true });
execFileSync("./node_modules/.bin/elm", ["make", "src/Main.elm", "--optimize", "--output", "dist/elm.js"], options);
await build({
  absWorkingDir: import.meta.dirname,
  entryPoints: ["src/bootstrap.ts"],
  bundle: true,
  minify: true,
  format: "iife",
  outfile: "dist/app.js",
  banner: { js: "// @generated by ui/build.mjs" },
});
cpSync("public/index.html", "dist/index.html");
cpSync("public/styles.css", "dist/styles.css");
